version: "3.8"

services:
  gen:
    build:
      context: .
      dockerfile: ./proto/Dockerfile
    command: ./proto/gen.sh
    volumes:
      - type: bind
        source: "./"
        target: "/proto"

  grpc_server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: "server/src"
        target: "/go/app/src"
    depends_on:
      - gen

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: "client"
        target: "/usr/app/src"
    depends_on:
      - gen
